"""add user management and analytics tables

Revision ID: 0e5221ac801d
Revises: 0d08a98674b0
Create Date: 2026-03-26 15:50:33.218206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e5221ac801d'
down_revision: Union[str, None] = '0d08a98674b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('metric_type', sa.String(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_metrics_date'), 'usage_metrics', ['date'], unique=False)
    op.create_index(op.f('ix_usage_metrics_id'), 'usage_metrics', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('user_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('activity_type', sa.String(), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_activities_id'), 'user_activities', ['id'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('appointment_type', sa.String(), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('diagnosis_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.add_column('chat_history', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('chat_history', 'session_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('chat_history', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('chat_history', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('chat_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'chat_history', 'users', ['user_id'], ['id'])
    op.add_column('diagnoses', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('diagnoses', sa.Column('full_report', sa.Text(), nullable=True))
    op.add_column('diagnoses', sa.Column('urgency_level', sa.String(), nullable=True))
    op.alter_column('diagnoses', 'treatment_plan',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('diagnoses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_diagnoses_patient_id'), table_name='diagnoses')
    op.drop_constraint(op.f('diagnoses_patient_id_fkey'), 'diagnoses', type_='foreignkey')
    op.create_foreign_key(None, 'diagnoses', 'patients', ['patient_id'], ['id'])
    op.create_foreign_key(None, 'diagnoses', 'users', ['user_id'], ['id'])
    op.add_column('image_analyses', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('image_analyses', 'image_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('image_analyses', 'original_filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('image_analyses', 'analysis_result',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=True)
    op.alter_column('image_analyses', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('image_analyses', 'severity',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('image_analyses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_image_analyses_patient_id'), table_name='image_analyses')
    op.drop_constraint(op.f('image_analyses_patient_id_fkey'), 'image_analyses', type_='foreignkey')
    op.create_foreign_key(None, 'image_analyses', 'users', ['user_id'], ['id'])
    op.add_column('medical_documents', sa.Column('metadata', sa.JSON(), nullable=True))
    op.alter_column('medical_documents', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               nullable=True)
    op.alter_column('medical_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('medical_documents', 'metadata_json')
    op.add_column('patients', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('patients', sa.Column('blood_type', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('allergies', sa.Text(), nullable=True))
    op.add_column('patients', sa.Column('chronic_conditions', sa.Text(), nullable=True))
    op.add_column('patients', sa.Column('emergency_contact', sa.String(), nullable=True))
    op.alter_column('patients', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('patients', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'patients', 'users', ['user_id'], ['id'])
    op.add_column('voice_interactions', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('voice_interactions', 'audio_filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('voice_interactions', 'language',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('voice_interactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_voice_interactions_patient_id'), table_name='voice_interactions')
    op.drop_constraint(op.f('voice_interactions_patient_id_fkey'), 'voice_interactions', type_='foreignkey')
    op.create_foreign_key(None, 'voice_interactions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'voice_interactions', type_='foreignkey')
    op.create_foreign_key(op.f('voice_interactions_patient_id_fkey'), 'voice_interactions', 'patients', ['patient_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_voice_interactions_patient_id'), 'voice_interactions', ['patient_id'], unique=False)
    op.alter_column('voice_interactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('voice_interactions', 'language',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('voice_interactions', 'audio_filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('voice_interactions', 'user_id')
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.alter_column('patients', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('patients', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('patients', 'emergency_contact')
    op.drop_column('patients', 'chronic_conditions')
    op.drop_column('patients', 'allergies')
    op.drop_column('patients', 'blood_type')
    op.drop_column('patients', 'user_id')
    op.add_column('medical_documents', sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.alter_column('medical_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('medical_documents', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               nullable=False)
    op.drop_column('medical_documents', 'metadata')
    op.drop_constraint(None, 'image_analyses', type_='foreignkey')
    op.create_foreign_key(op.f('image_analyses_patient_id_fkey'), 'image_analyses', 'patients', ['patient_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_image_analyses_patient_id'), 'image_analyses', ['patient_id'], unique=False)
    op.alter_column('image_analyses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('image_analyses', 'severity',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('image_analyses', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('image_analyses', 'analysis_result',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('image_analyses', 'original_filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('image_analyses', 'image_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('image_analyses', 'user_id')
    op.drop_constraint(None, 'diagnoses', type_='foreignkey')
    op.drop_constraint(None, 'diagnoses', type_='foreignkey')
    op.create_foreign_key(op.f('diagnoses_patient_id_fkey'), 'diagnoses', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_diagnoses_patient_id'), 'diagnoses', ['patient_id'], unique=False)
    op.alter_column('diagnoses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('diagnoses', 'treatment_plan',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('diagnoses', 'urgency_level')
    op.drop_column('diagnoses', 'full_report')
    op.drop_column('diagnoses', 'user_id')
    op.drop_constraint(None, 'chat_history', type_='foreignkey')
    op.alter_column('chat_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_history', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('chat_history', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('chat_history', 'session_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('chat_history', 'user_id')
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_user_activities_id'), table_name='user_activities')
    op.drop_table('user_activities')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_usage_metrics_id'), table_name='usage_metrics')
    op.drop_index(op.f('ix_usage_metrics_date'), table_name='usage_metrics')
    op.drop_table('usage_metrics')
    # ### end Alembic commands ###
